######################################################################
# Automatically generated by qmake (3.0) Dum dec. 18 20:32:10 2016
######################################################################

TEMPLATE = app
TARGET = qt
INCLUDEPATH += .

# Input
HEADERS += controller.h histogram_view.h
SOURCES += controller.cpp histogram_view.cpp main.cpp
