#!/bin/bash
# hash count
DICT="$(head -n 1000 dictionaries/all.txt)"
OUTPUTFILE="out.txt"
# compute the hashes from all the words in dictionary
while read line; 
do
	# words="${words}\n${line}";
	tmp="${tmp}"$'\n'"`echo -n $line | md5sum | awk '{print $1}'`"; 
done <<< "${DICT}"

echo -e $tmp | tr " " "\n"> $OUTPUTFILE 
